services:
  - type: web
    name: pan-majster
    runtime: python
    branch: pan-majster
    plan: free
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3

